[workspace]
authors = ["KaseyMCastello <kcastello@ucsd.edu>"]
channels = ["conda-forge"]
name = "ohw25_proj_RiptideRemix"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.4.6,<5"
pixi-kernel = ">=0.6.6,<0.7"
copernicusmarine = ">=2.2.1,<3"
xarray = ">=2025.8.0,<2026"
cartopy = ">=0.25.0,<0.26"
matplotlib = ">=3.10.5,<4"
hvplot = ">=0.12.0,<0.13"
numpy = ">=2.3.2,<3"
marimo = ">=0.14.17,<0.15"
scipy = ">=1.16.1,<2"
ipython = ">=9.4.0,<10"
ipy = ">=1.1,<2"
obspy = ">=1.4.2,<2"
python = ">=3.12.11,<3.13"
jupyterlab-git = ">=0.51.2,<0.52"
shapely = ">=2.1.1,<3"
jupyter = ">=1.1.1,<2"
ipywidgets = ">=8.1.7,<9"
ffmpeg = ">=7.1.1,<8"
ffmpeg-python = ">=0.2.0,<0.3"
paramiko = ">=4.0.0,<5"
bokeh = ">=3.7.3,<4"
holoviews = ">=1.21.0,<2"
pandas = ">=2.2.3,<3"
zarr = ">=3.1.1,<4"
imageio = ">=2.37.0,<3"
selenium = ">=4.35.0,<5"
firefox = ">=141.0.3,<142"
geckodriver = ">=0.36.0,<0.37"
pydub = ">=0.25.1,<0.26"
